### ISSUE TITLE
Nefunguje

### ISSUE THREAD

**Issue by Zvady** [cache-sk/SkTonline#1]
Nefunguje = prosím doplnit funkci aby se dalo přihlásit na WEB , protože jen pak se dá koukat. díky

**Comment by cache-sk** [comment]
Na toto som uz odpovedal aj na fore - tuto limitaciu zaviedli len pre CZ region, na slovensku vsetko funguje po starom.
Vec, ktoru nedokazem vidiet nedokazem ani naprogramovat, cize inak povedane - je to v poradi a ked budem mat vyriesene akutnejsie veci (doplnkom sa uz venujem len okrajovo) a zozeniem si nejaku VPN do ciech, tak to mozem zapracovat. Skor nie. Bohuzial.

**Comment by Zvady** [comment]
A môžem ťa poprosiť o odkaz na forum kde sa to rieši :P alebo vieš mi poradit aj iný podobný doplnok, viem že sú rôzne serialove a filmove "free"weby.

**Comment by cache-sk** [comment]
https://www.xbmc-kodi.cz/prispevek-sktonline?pid=113787#pid113787

skusil som spravit moznost prihlasenia, otestuj

**Comment by Zvady** [comment]
Vyskúšam a ďakujem =  nie je treba update dopňku?

**Comment by cache-sk** [comment]
samozrejme, idealne mat pridany repozitar, aby aktualizacie chodili sami - http://p.xf.cz/r
